import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { getCurrentlyPlayingTrackFromToken } from "./api/refresh_token";

type Props = {
  name: string;
  image: string;
};

const Home: NextPage<Props> = (props: Props) => {
  const { name, image } = props;



  return (
    <div>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className={"hidden"}>{name}</h1>
        <img src={image} alt="" />
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps<Props> = async (
  context
) => {
  const data = await getCurrentlyPlayingTrackFromToken(
    "AQDWpCB3mG1vYSqGaGaeeFtWfKXzzNHZ2QVfqUASdASj3vgXFqMVFCvalYYVLnvp6QVBCnnn3b5Mhh-M_HTQOkoMNqjKAgwKhyklUCkTeaDxaDnDWlht_Q2nVGjHZRCxzeI"
  );
  const album = data.item.album;

  return {
    props: {
      name: album.name as string,
      image: album.images[0].url as string,
    },
  };
};

export default Home;
