import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Spotify Watcher</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"h-screen bg-black flex justify-center items-center"}>
        <Link href="/login">
          <a className="text-blue-600 font-bold">ログインページへ</a>
        </Link>
      </main>
    </>
  );
};

export default Home;
